# ================================================= # 
#  Settings of the SDR interface.                   # 
#  Allows the saving of sessions for later use.     # 
# ================================================= # 

#  Filing settings.
folder: None
file-latest: None
file-target: None
auto-filing: Enabled

#  SDR settings.
sample-rate-tx: 4000000
sample-rate-rx: 4000000
wave-frequency-tx: 520000000
wave-frequency-rx: 520000000
gain-tx: 20
gain-rx: 10
filter-bandwidth-tx: 8000000
filter-bandwidth-rx: 8000000

#  Device settings.
clock-ref: internal
channels-tx: 0
channels-rx: 0
antenna-tx: ""
antenna-rx: ""

# ================================================= #