# ================================================= # 
#  Settings of the SDR interface.                   # 
#  Allows the saving of sessions for later use.     # 
# ================================================= # 

#  Filing settings.
folder: Data\Testing
file-latest: B210_SAMPLES_Testing_1.bin
file-target: B210_SAMPLES_Testing_2.bin
auto-filing: Enabled

#  Radar settings.
max-range: 100
tx-duration: 1

#  SDR settings.
sample-rate-tx: 12000000
sample-rate-rx: 12000000
wave-frequency-tx: 900000000
wave-frequency-rx: 900000000
gain-tx: 40
gain-rx: 0
filter-bandwidth-tx: 10000000
filter-bandwidth-rx: 10000000

#  Device settings.
clock-ref: internal
channels-tx: 0
channels-rx: 0
antenna-tx: ""
antenna-rx: ""

# ================================================= #