# ================================================= # 
#  Settings of the SDR interface.                   # 
#  Allows the saving of sessions for later use.     # 
# ================================================= # 

#  Filing settings.
folder: Data\Testing
file-latest: Empty folder
file-target: B210_SAMPLES_Testing_0.txt
auto-filing: Enabled

#  SDR settings.
sample-rate-tx: 4000000
sample-rate-rx: 4000000
wave-frequency-tx: 900000000
wave-frequency-rx: 900000000
gain-tx: 80
gain-rx: 0
filter-bandwidth-tx: 10000000
filter-bandwidth-rx: 10000000

#  Device settings.
clock-ref: internal
channels-tx: 0
channels-rx: 0
antenna-tx: ""
antenna-rx: ""

# ================================================= #