# ================================================= # 
#  Settings of the SDR interface.                   # 
#  Allows the saving of sessions for later use.     # 
# ================================================= # 

#  Filing settings.
folder: Data\Testing
file-latest: B210_SAMPLES_Testing_44.bin
file-target: B210_SAMPLES_Testing_45.bin
auto-filing: Enabled

#  Radar settings.
max-range: 1000
tx-duration: 10
dead-zone: 155

#  SDR settings.
sample-rate-tx: 8000000
sample-rate-rx: 8000000
wave-frequency-tx: 900000000
wave-frequency-rx: 900000000
gain-tx: 80
gain-rx: 0
filter-bandwidth-tx: 10000000
filter-bandwidth-rx: 10000000

#  Device settings.
clock-ref: internal
channels-tx: 0
channels-rx: 0
antenna-tx: ""
antenna-rx: ""

# ================================================= #