# ================================================= # 
#  Settings of the SDR interface.                   # 
#  Allows the saving of sessions for later use.     # 
# ================================================= # 

#  Filing settings.
folder: Data\Testing
file-latest: B210_SAMPLES_Testing_13.bin
file-target: B210_SAMPLES_Testing_14.bin
auto-filing: Enabled

#  Radar settings.
max-range: 400
tx-duration: 3
dead-zone: 100
window-function: None

#  SDR settings.
sample-rate-tx: 12000000
sample-rate-rx: 12000000
wave-frequency-tx: 900000000
wave-frequency-rx: 900000000
gain-tx: 60
gain-rx: 0
filter-bandwidth-tx: 20000000
filter-bandwidth-rx: 20000000

#  Device settings.
clock-ref: internal
channels-tx: 0
channels-rx: 0
antenna-tx: ""
antenna-rx: ""

# ================================================= #